

List<Map<String, dynamic>> sampleDataList = [
  {
    'companyName': 'Webrexo',
    'contactName': 'Marif',
    'email': 'john.doe@example.com',
    'date': 'October 15, 2023',
    'additionalInfo1': 'Additional Info 1A',
    'additionalInfo2': 'Additional Info 2A',
  },
  {
    'companyName': 'Webrexo',
    'contactName': 'Marif',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Webrexo',
    'contactName': 'Marif',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Webrexo',
    'contactName': 'Marif',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Webrexo',
    'contactName': 'Marif',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Webrexo',
    'contactName': 'Marif',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Webrexo',
    'contactName': 'Marif',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Company B',
    'contactName': 'Jane Smith',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Company B',
    'contactName': 'Jane Smith',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Company B',
    'contactName': 'Jane Smith',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
  {
    'companyName': 'Company B',
    'contactName': 'Jane Smith',
    'email': 'jane.smith@example.com',
    'date': 'November 20, 2023',
    'additionalInfo1': 'Additional Info 1B',
    'additionalInfo2': 'Additional Info 2B',
  },
];
